stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - litmus-chaos
  - cleanup
  - deploy
azure-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 755 ./script/azure
    - ./script/azure

  artifacts:
    paths:
      - azoebs_aks_name/

openebs-deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - azure-cluster
  script: 
   - echo "deploying OpenEBS on Azure"
   - ls
   - chmod 775 ./script/infra-setup
   - ./script/infra-setup
  
  artifacts:
    paths:
      - azure/

percona-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-deploy
  script: 
   - echo "jobs-Azure-Started"
   - chmod 775 ./script/percona-app-deploy
   - ./script/percona-app-deploy

  artifacts:
    paths:
      - azure/

jenkins-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-deploy
  script: 
   - echo "jobs-Azure-Started"
   - chmod 775 ./script/jenkins-app-deploy
   - ./script/jenkins-app-deploy

  artifacts:
    paths:
      - azure/

cassandra-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-deploy
  script: 
   - echo "jobs-Azure-Started"
   - chmod 775 ./script/cassandra-app-deploy
   - ./script/cassandra-app-deploy

  artifacts:
    paths:
      - azure/

mongo-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-deploy
  script: 
   - echo "jobs-Azure-Started"
   - chmod 775 ./script/mongo-app-deploy
   - ./script/mongo-app-deploy

  artifacts:
    paths:
      - azure/

postgres-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-deploy
  script: 
   - echo "jobs-Azure-Started"
   - chmod 775 ./script/postgres-app-deploy
   - ./script/postgres-app-deploy

  artifacts:
    paths:
      - azure/

litmus-chaos:
  image: atulabhi/kops:v8
  dependencies:
    - percona-deploy
  stage: litmus-chaos
  script:
   - chmod 775 ./script/app-chaos
   - ./script/app-chaos

cleanup-azure:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - azure-cluster
  stage: cleanup
  script: 
    - chmod 755 ./script/azure-cleanup
    - ./script/azure-cleanup
